server: 
  port: 8060
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
         - id: onboarding-service
           uri: lb://onboarding-service
           predicates:
            - Path= /customers/**
         - id: processing-service
           uri: lb://processing-service
           predicates:
            - Path= /processing/**
  config:
   import:    "configserver:http://localhost:8088"


    
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/